// seed.js
import { Producto } from "./models.js";

export const productosSeed = [
  new Producto(
    1,
    "Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    6000,
    70000,
    ["/assets/img/productos/Dragon Ball/001-goku.png"],
    "/assets/img/productos/Dragon Ball/001-goku.gif",
    "Figura coleccionable de Goku con su icónico traje naranja y azul.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    2,
    "Vegeta",
    "Dragon Ball",
    "7-8cm",
    8000,
    6000,
    210000,
    ["/assets/img/productos/Dragon Ball/002-vegeta.png"],
    "/assets/img/productos/Dragon Ball/002-vegeta.gif",
    "Control DualSense edición especial Kimetsu no Yaiba.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    3,
    "Goku SS4",
    "Dragon Ball",
    "10 cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/003-gokuss4.png"],
    "/assets/img/productos/Dragon Ball/003-gokuss4.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    4,
    "Gohan",
    "Dragon Ball",
    "13 cm",
    8000,
    6000,
    70000,
    ["/assets/img/productos/Dragon Ball/004-gohan.png"],
    "/assets/img/productos/Dragon Ball/004-gohan.gif",
    "Figura detallada de Naruto en modo sabio.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    5,
    "Black Goku SSJ Rose",
    "Dragon Ball",
    "N/A",
    8000,
    6000,
    210000,
    ["/assets/img/productos/Dragon Ball/005-samas.png"],
    "/assets/img/productos/Dragon Ball/005-samas.gif",
    "Control DualSense edición especial Kimetsu no Yaiba.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    6,
    "Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/006-goku.png"],
    "/assets/img/productos/Dragon Ball/006-goku.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    7,
    "Goku SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/007-gokublue.png"],
    "/assets/img/productos/Dragon Ball/007-gokublue.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    8,
    "Zen Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/008-zengoku.png"],
    "/assets/img/productos/Dragon Ball/008-zengoku.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    2,
    null,
    1
  ),
  new Producto(
    9,
    "Vegeta SSJ Rose",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/009-vegetarose.png"],
    "/assets/img/productos/Dragon Ball/009-vegetarose.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    10,
    "Black Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/010-blackgoku.png"],
    "/assets/img/productos/Dragon Ball/010-blackgoku.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    2,
    null,
    1
  ),
  new Producto(
    11,
    "Goku SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/011-gokussj.png"],
    "/assets/img/productos/Dragon Ball/011-gokussj.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    12,
    "Gogeta SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/012-gogetassj.png"],
    "/assets/img/productos/Dragon Ball/012-gogetassj.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    13,
    "Vegeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/013-vegetablue.png"],
    "/assets/img/productos/Dragon Ball/013-vegetablue.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    14,
    "Vegeto SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/014-vegetossj.png"],
    "/assets/img/productos/Dragon Ball/014-vegetossj.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    15,
    "Gotenks SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/015-gotenksssj.png"],
    "/assets/img/productos/Dragon Ball/015-gotenksssj.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    16,
    "Vegeta Traje Naranja",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/016-vegetanaranja.png"],
    "/assets/img/productos/Dragon Ball/016-vegetanaranja.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    17,
    "Zen Vegeta",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/017-zenvegeta.png"],
    "/assets/img/productos/Dragon Ball/017-zenvegeta.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    18,
    "Vegeto Traje Naranja",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/018-vegetonaranja.png"],
    "/assets/img/productos/Dragon Ball/018-vegetonaranja.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    19,
    "Gogeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/019-gogetablue.png"],
    "/assets/img/productos/Dragon Ball/019-gogetablue.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    20,
    "Gotenks",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/020-gotenks.png"],
    "/assets/img/productos/Dragon Ball/020-gotenks.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    21,
    "Vegeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/021-vegetablue.png"],
    "/assets/img/productos/Dragon Ball/021-vegetablue.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    22,
    "Vegeto SSJ 2",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/022-vegetossj2.png"],
    "/assets/img/productos/Dragon Ball/022-vegetossj2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    100,
    "Metal Cooler",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/100-metalcooler.png"],
    "/assets/img/productos/Dragon Ball/100-metalcooler.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg",
    1
  ),
  new Producto(
    101,
    "Lunch",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/101-lunch.png"],
    "/assets/img/productos/Dragon Ball/101-lunch2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg"
  ),
  new Producto(
    102,
    "Gran Patriarca",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/102-granpatriarca.png"],
    "/assets/img/productos/Dragon Ball/102-granpatriarca2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg"
  ),
  new Producto(
    103,
    "Turles",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/103-turles.png"],
    "/assets/img/productos/Dragon Ball/103-turles.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    104,
    "Gogeta SSJ",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/104-gogetassj.png"],
    "/assets/img/productos/Dragon Ball/104-gogetassj.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    200,
    "Hildegan",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/200-hildegan.png"],
    "/assets/img/productos/Dragon Ball/200-hildegan.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    201,
    "Porunga",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/201-porunga.png"],
    "/assets/img/productos/Dragon Ball/201-porunga2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    202,
    "Vegeta Osaru",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/productos/Dragon Ball/202-vegetaosaru.png"],
    "/assets/img/productos/Dragon Ball/202-vegetaosaru.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    230,
    "Dende",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Dragon Ball/230-dende.png"],
    "/assets/img/productos/Dragon Ball/230-dende.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    230,
    "Krillin",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Dragon Ball/231-krilin.png"],
    "/assets/img/productos/Dragon Ball/231-krilin.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 3
  ),
  new Producto(
    1000,
    "Hinata Hyuga",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1000-hinata.png"],
    "/assets/img/productos/Naruto/1000-hinata2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1001,
    "Sasuke Uchiha",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1001-sasuke.png"],
    "/assets/img/productos/Naruto/1001-sasuke3.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1002,
    "Sakura Haruno",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1002-sakura.png"],
    "/assets/img/productos/Naruto/1002-sakura2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1003,
    "Gaara",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1003-gaara.png"],
    "/assets/img/productos/Naruto/1003-gaara.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1030,
    "Sasuke Uchiha",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1030-sasukeuchiha.png"],
    "/assets/img/productos/Naruto/1030-sasukeuchiha3.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    , 2
  ),
  new Producto(
    1031,
    "Naruto Uzumaki",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1031-naruto.png"],
    "/assets/img/productos/Naruto/1031-naruto2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    , 2
  ),
  new Producto(
    1032,
    "Naruto VS Sasuke",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1032-sasukevsnaruto.png"],
    "/assets/img/productos/Naruto/1032-sasukevsnaruto4.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    ,
    2
  ),
  
  new Producto(
    1033,
    "Naruto Modo Sabio",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/Naruto/1033-narutosabio.png"],
    "/assets/img/productos/Naruto/1033-narutosabio.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto.jpg" // 👈 fondo específico para este producto
    , 3
  ),

  new Producto(
    2000,
    "Inosuke Hashibira",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2000-InosukeHashibira.png"],
    "/assets/img/productos/DemonSlayer/2000-InosukeHashibira.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),

  new Producto(
    2001,
    "Giyu Tomioka",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2001-giyutomioka.png"],
    "/assets/img/productos/DemonSlayer/2001-giyutomioka2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),
  new Producto(
    2001,
    "Tanjiro Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2002-TanjiroKamado.png"],
    "/assets/img/productos/DemonSlayer/2002-TanjiroKamado.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),
  new Producto(
    2002,
    "Nezuko Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2002-NezukoKaKmado.png"],
    "/assets/img/productos/DemonSlayer/2002-NezukoKamado.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),
  new Producto(
    2003,
    "Zenitsu Agatsuma",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2003-ZenitsuAgatsuma.png"],
    "/assets/img/productos/DemonSlayer/2003-ZenitsuAgatsuma.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),

  new Producto(
    2004,
    "Tanjiro Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/20024-TanjiroKamadoKimono.png"],
    "/assets/img/productos/DemonSlayer/2004-TanjiroKamadoKimono.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
  ),

  new Producto(
    2050,
    "Inosuke Hashibira",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/productos/DemonSlayer/2050-InosukeHashibira.png"],
    "/assets/img/productos/DemonSlayer/2050-InosukeHashibira2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
    ,
    4
  ),
  
];
