// seed.js
import { Producto } from "./models.js";

export const productosSeed = [
  new Producto(
    1,
    "Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    6000,
    70000,
    ["/assets/img/img/Dragon Ball/001-goku.png"],
    "/assets/img/gif/Dragon Ball/001-goku-min.gif",
    "Figura coleccionable de Goku con su icónico traje naranja y azul.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    2,
    "Vegeta",
    "Dragon Ball",
    "7-8cm",
    8000,
    6000,
    210000,
    ["/assets/img/img/Dragon Ball/002-vegeta.png"],
    "/assets/img/gif/Dragon Ball/002-vegeta-min.gif",
    "Control DualSense edición especial Kimetsu no Yaiba.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    3,
    "Goku SS4",
    "Dragon Ball",
    "10 cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/003-gokuss4.png"],
    "/assets/img/gif/Dragon Ball/003-gokuss4-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    4,
    "Gohan",
    "Dragon Ball",
    "13 cm",
    8000,
    6000,
    70000,
    ["/assets/img/img/Dragon Ball/004-gohan.png"],
    "/assets/img/gif/Dragon Ball/004-gohan-min.gif",
    "Figura detallada de Naruto en modo sabio.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    5,
    "Black Goku SSJ Rose",
    "Dragon Ball",
    "N/A",
    8000,
    6000,
    210000,
    ["/assets/img/img/Dragon Ball/005-samas.png"],
    "/assets/img/gif/Dragon Ball/005-samas-min.gif",
    "Control DualSense edición especial Kimetsu no Yaiba.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    6,
    "Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/006-goku.png"],
    "/assets/img/gif/Dragon Ball/006-goku-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    7,
    "Goku SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/007-gokublue.png"],
    "/assets/img/gif/Dragon Ball/007-gokublue-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    8,
    "Zen Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/008-zengoku.png"],
    "/assets/img/gif/Dragon Ball/008-zengoku-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    2,
    null,
    1
  ),
  new Producto(
    9,
    "Vegeta SSJ Rose",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/009-vegetarose.png"],
    "/assets/img/gif/Dragon Ball/009-vegetarose-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    10,
    "Black Goku",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/010-blackgoku.png"],
    "/assets/img/gif/Dragon Ball/010-blackgoku-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    2,
    null,
    1
  ),
  new Producto(
    11,
    "Goku SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/011-gokussj.png"],
    "/assets/img/gif/Dragon Ball/011-gokussj-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    12,
    "Gogeta SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/012-gogetassj.png"],
    "/assets/img/gif/Dragon Ball/012-gogetassj-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    13,
    "Vegeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/013-vegetablue.png"],
    "/assets/img/gif/Dragon Ball/013-vegetablue-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    14,
    "Vegeto SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/014-vegetossj.png"],
    "/assets/img/gif/Dragon Ball/014-vegetossj-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    15,
    "Gotenks SSJ",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/015-gotenksssj.png"],
    "/assets/img/gif/Dragon Ball/015-gotenksssj-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    16,
    "Vegeta Traje Naranja",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/016-vegetanaranja.png"],
    "/assets/img/gif/Dragon Ball/016-vegetanaranja-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    17,
    "Zen Vegeta",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/017-zenvegeta.png"],
    "/assets/img/gif/Dragon Ball/017-zenvegeta-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    18,
    "Vegeto Traje Naranja",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/018-vegetonaranja.png"],
    "/assets/img/gif/Dragon Ball/018-vegetonaranja-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    1,
    null,
    1
  ),
  new Producto(
    19,
    "Gogeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/019-gogetablue.png"],
    "/assets/img/gif/Dragon Ball/019-gogetablue-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    20,
    "Gotenks",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/020-gotenks.png"],
    "/assets/img/gif/Dragon Ball/020-gotenks-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    21,
    "Vegeta SSJ Blue",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/021-vegetablue.png"],
    "/assets/img/gif/Dragon Ball/021-vegetablue-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    22,
    "Vegeto SSJ 2",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/022-vegetossj2.png"],
    "/assets/img/gif/Dragon Ball/022-vegetossj2-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),

  new Producto(
    23,
    "Kid Buu",
    "Dragon Ball",
    "7-8cm",
    8000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/023-kidbuu.png"],
    "/assets/img/gif/Dragon Ball/023-kidbuu-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    null,
    1
  ),
  new Producto(
    100,
    "Metal Cooler",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/100-metalcooler.png"],
    "/assets/img/gif/Dragon Ball/100-metalcooler-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg",
    2
  ),
  new Producto(
    101,
    "Lunch",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/101-lunch.png"],
    "/assets/img/gif/Dragon Ball/101-lunch2-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg",
    2
  ),
  new Producto(
    102,
    "Gran Patriarca",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/102-granpatriarca.png"],
    "/assets/img/gif/Dragon Ball/102-granpatriarca2-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg",
    2
  ),
  new Producto(
    103,
    "Turles",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/103-turles.png"],
    "/assets/img/gif/Dragon Ball/103-turles-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg",
        2
  ),
  new Producto(
    104,
    "Gogeta SSJ",
    "Dragon Ball",
    "7-8cm",
    10000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/104-gogetassj.png"],
    "/assets/img/gif/Dragon Ball/104-gogetassj-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz2.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    200,
    "Hildegan",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/200-hildegan.png"],
    "/assets/img/gif/Dragon Ball/200-hildegan-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    201,
    "Porunga",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/201-porunga.png"],
    "/assets/img/gif/Dragon Ball/201-porunga2-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    202,
    "Vegeta Osaru",
    "Dragon Ball",
    "7-8cm",
    12000,
    null,
    50000,
    ["/assets/img/img/Dragon Ball/202-vegetaosaru.png"],
    "/assets/img/gif/Dragon Ball/202-vegetaosaru-min.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz6jpg.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    230,
    "Dende",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/230-dende.png"],
    "/assets/img/gif/Dragon Ball/230-dende.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    230,
    "Krillin",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/231-krilin.png"],
    "/assets/img/gif/Dragon Ball/231-krilin.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    300,
    "Mayin Buu Corriendo",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/300-MayinBuuCorriendo.png"],
    "/assets/img/gif/Dragon Ball/300-MayinBuuCorriendo.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    301,
    "Mayin Buu Dominadas",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/301-MayinBuuDominadas.png"],
    "/assets/img/gif/Dragon Ball/301-MayinBuuDominadas.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),
  new Producto(
    302,
    "Mayin Buu Press Banca",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/302-MayinBuuPesas.png"],
    "/assets/img/gif/Dragon Ball/302-MayinBuuPesas.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),

  new Producto(
    303,
    "Mayin Buu Equilibrio",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/303-MayinBuuEquilibrio.png"],
    "/assets/img/gif/Dragon Ball/303-MayinBuuEquilibrio.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 2
  ),

  new Producto(
    310,
    "Mayin Buu Gotenks",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/310-MiniMayinBuuGotenks.png"],
    "/assets/img/gif/Dragon Ball/310-MiniMayinBuuGotenks.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  new Producto(
    311,
    "Mayin Buu",
    "Dragon Ball",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Dragon Ball/311-MiniMayinBuuCapa.png"],
    "/assets/img/gif/Dragon Ball/311-MiniMayinBuuCapa.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 1
  ),
  
  

  new Producto(
    320,
    "Gran Mayin Buu",
    "Dragon Ball",
    "7-8cm",
    50000,
    35000,
    50000,
    ["/assets/img/img/Dragon Ball/320-granmayinbuu.png"],
    "/assets/img/gif/Dragon Ball/320-granmayinbuu.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 4
  ),

  new Producto(
    321,
    "Kid Buu",
    "Dragon Ball",
    "7-8cm",
    50000,
    30000,
    50000,
    ["/assets/img/img/Dragon Ball/321-KidBuu.png"],
    "/assets/img/gif/Dragon Ball/321-KidBuu.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodbz5.jpg" // 👈 fondo específico para este producto
        , 3
  ),
  
  

  
  new Producto(
    1000,
    "Hinata Hyuga",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1000-hinata.png"],
    "/assets/img/gif/Naruto/1000-hinata2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1001,
    "Sasuke Uchiha",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1001-sasuke.png"],
    "/assets/img/gif/Naruto/1001-sasuke3.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1002,
    "Sakura Haruno",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1002-sakura.png"],
    "/assets/img/gif/Naruto/1002-sakura2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1003,
    "Gaara",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1003-gaara.png"],
    "/assets/img/gif/Naruto/1003-gaara.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 1
  ),
  new Producto(
    1030,
    "Sasuke Uchiha",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1030-sasukeuchiha.png"],
    "/assets/img/gif/Naruto/1030-sasukeuchiha3.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    , 3
  ),
  new Producto(
    1031,
    "Naruto Uzumaki",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1031-naruto.png"],
    "/assets/img/gif/Naruto/1031-naruto2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    , 3
  ),
  new Producto(
    1032,
    "Naruto VS Sasuke",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1032-sasukevsnaruto.png"],
    "/assets/img/gif/Naruto/1032-sasukevsnaruto4.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto2.jpg" // 👈 fondo específico para este producto
    ,
    4
  ),
  
  new Producto(
    1033,
    "Naruto Modo Sabio",
    "Naruto",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/Naruto/1033-narutosabio.png"],
    "/assets/img/gif/Naruto/1033-narutosabio.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondonaruto1.jpg" // 👈 fondo específico para este producto
    , 4
  ),

  new Producto(
    2000,
    "Inosuke Hashibira",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2000-InosukeHashibira.png"],
    "/assets/img/gif/DemonSlayer/2000-InosukeHashibira.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),

  new Producto(
    2001,
    "Giyu Tomioka",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2001-giyutomioka.png"],
    "/assets/img/gif/DemonSlayer/2001-giyutomioka2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),
  new Producto(
    2002,
    "Tanjiro Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2002-TanjiroKamado.png"],
    "/assets/img/gif/DemonSlayer/2002-TanjiroKamado.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),
  new Producto(
    2003,
    "Nezuko Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2003-NezukoKaKmado.png"],
    "/assets/img/gif/DemonSlayer/2003-NezukoKamado.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),
  new Producto(
    2004,
    "Zenitsu Agatsuma",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2004-ZenitsuAgatsuma.png"],
    "/assets/img/gif/DemonSlayer/2004-ZenitsuAgatsuma.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),

  new Producto(
    2005,
    "Tanjiro Kamado",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2005-TanjiroKamadoKimono.png"],
    "/assets/img/gif/DemonSlayer/2005-TanjiroKamadoKimono.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer.png" // 👈 fondo específico para este producto
  ),

  new Producto(
    2050,
    "Zenitsu Agatsuma",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2050-ZenitsuAgatsuma.png"],
    "/assets/img/gif/DemonSlayer/2050-ZenitsuAgatsuma.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
    ,
    2
  ),
    new Producto(
    2051,
    "Inosuke Hashibira",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2051-InosukeHashibira.png"],
    "/assets/img/gif/DemonSlayer/2051-InosukeHashibira2.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
    ,
    2
  ),
  new Producto(
    2052,
    "Sabito",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2052-Sabito.png"],
    "/assets/img/gif/DemonSlayer/2052-Sabito.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
    ,
    2
  ),

  new Producto(
    2053,
    "Enmu",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2053-Enmu.png"],
    "/assets/img/gif/DemonSlayer/2053-Enmu.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer2.jpg" // 👈 fondo específico para este producto
    ,
    2
  ),

  new Producto(
    2100,
    "Zenitsu Agatsuma",
    "Demon Slayer",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/DemonSlayer/2100-ZenitsuAgatsuma.png"],
    "/assets/img/gif/DemonSlayer/2100-ZenitsuAgatsuma3.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondodemonslayer3.png" // 👈 fondo específico para este producto
    ,
    3
  ),

  

  new Producto(
    6000,
    "Harry Potter",
    "Harry Potter",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/HarryPotter/6000-HarryEscoba.png"],
    "/assets/img/gif/HarryPotter/6000-HarryEscoba.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondoharry1.png" // 👈 fondo específico para este producto
    ,
    2
  ),

  new Producto(
    6001,
    "Ron Weasley",
    "Harry Potter",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/HarryPotter/6001-RonEscoba.png"],
    "/assets/img/productos/HarryPotter/6001-RonEscoba.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondoharry1.png" // 👈 fondo específico para este producto
    ,
    2
  ),

  new Producto(
    6005,
    "Ron Weasley",
    "Harry Potter",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/HarryPotter/6005-RonSentado.png"],
    "/assets/img/gif/HarryPotter/6005-RonSentado.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondoharry1.png" // 👈 fondo específico para este producto
    ,
    2
  ),

  new Producto(
    6006,
    "Hermione Granger",
    "Harry Potter",
    "7-8cm",
    18000,
    15000,
    50000,
    ["/assets/img/img/HarryPotter/6006-HermioneGranger.png"],
    "/assets/img/gif/HarryPotter/6006-HermioneGranger.gif",
    "Edición especial Funko Pop Demon Slayer.",
    "Disponible",
    8,
    "/assets/img/fondos/fondoharry1.png" // 👈 fondo específico para este producto
    ,
    2
  ),

  

  
];
